[2018-05-24 12:59:46 +0000] [5083] [INFO] Starting gunicorn 19.8.1
[2018-05-24 12:59:46 +0000] [5083] [INFO] Listening at: http://127.0.0.1:8000 (5083)
[2018-05-24 12:59:46 +0000] [5083] [INFO] Using worker: sync
[2018-05-24 12:59:46 +0000] [5087] [INFO] Booting worker with pid: 5087
[2018-05-24 12:59:46 +0000] [5087] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named 127.0.0.1
[2018-05-24 12:59:46 +0000] [5087] [INFO] Worker exiting (pid: 5087)
[2018-05-24 12:59:46 +0000] [5083] [INFO] Shutting down: Master
[2018-05-24 12:59:46 +0000] [5083] [INFO] Reason: Worker failed to boot.
[2018-05-24 13:05:44 +0000] [6187] [INFO] Starting gunicorn 19.8.1
[2018-05-24 13:05:44 +0000] [6187] [INFO] Listening at: http://127.0.0.1:8000 (6187)
[2018-05-24 13:05:44 +0000] [6187] [INFO] Using worker: sync
[2018-05-24 13:05:44 +0000] [6192] [INFO] Booting worker with pid: 6192
[2018-05-24 13:05:44 +0000] [6192] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named 127.0.0.1
[2018-05-24 13:05:44 +0000] [6192] [INFO] Worker exiting (pid: 6192)
[2018-05-24 13:05:44 +0000] [6187] [INFO] Shutting down: Master
[2018-05-24 13:05:44 +0000] [6187] [INFO] Reason: Worker failed to boot.
[2018-05-24 13:08:52 +0000] [7374] [INFO] Starting gunicorn 19.8.1
[2018-05-24 13:08:52 +0000] [7374] [INFO] Listening at: http://127.0.0.1:8000 (7374)
[2018-05-24 13:08:52 +0000] [7374] [INFO] Using worker: sync
[2018-05-24 13:08:52 +0000] [7378] [INFO] Booting worker with pid: 7378
[2018-05-24 13:08:52 +0000] [7378] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/vincent/work/git0517/fangkexitong/python/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named 127.0.0.1
[2018-05-24 13:08:52 +0000] [7378] [INFO] Worker exiting (pid: 7378)
[2018-05-24 13:08:52 +0000] [7374] [INFO] Shutting down: Master
[2018-05-24 13:08:52 +0000] [7374] [INFO] Reason: Worker failed to boot.
